repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: detect-aws-credentials



-  repo: https://github.com/compilerla/conventional-pre-commit
   rev: v2.1.1
   hooks:

   - id: conventional-pre-commit
     stages: [commit-msg]
     args: []

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.88.4
  hooks:
    - id: terraform_fmt